#!/bin/bash
function menu(){
OPCAO=$(dialog					\
	--stdout				\
	--menu "Gerenciador de dispositivos"	\
	0 0 0					\
	1 "Data e hora do sistema"		\
	2 "Calendário"				\
	3 "Alterar data do sistema"		\
	4 "Alterar hora do sistema"		\
	5 "Informações da cpu"			\
	6 "Informações de disco e partições"	\
	7 "Visualizar modulos carregados"	\
	8 "Informações do barramento PCI" 	\
	9 "Utilização de memória RAM"		\
	10 "Quantidade de INODES disponíveis"	\
	11 "Versão do Kernel "			\
	12 "Todas informações do sistema"	\
	13 "Processos do sistema"		\
	14 "Processos do sistema de forma hierarquica" \
	15 "Fechar processos" 			\
	16 "Arquivos abertos no sistema" \
	17 "Ver INODE"				\
	18 "Voltar" )
case $OPCAO in
	1) MDAEH ;;
	2) CALEN ;;
	3) EDATA ;;
	4) EHORA ;;
	5) INFCP ;;
	6) EXDP ;;
	7) MODC ;;
	8) PCI2 ;;
	9) UTM ;;
	10) IND ;;
	11) KERNEL ;;
	12) ALLINF ;;
	13) PROCSIS ;;
	14) PROCSISH ;;
	15) KILLPROC ;;
	16) ARQPROC ;;
	17) VINOD ;;
	18) bash /Projeto/.config/menu.sh ;;
	*) bash /Projeto/.config/menu.sh ;;
esac
}
# O usuário escolhe uma das opções de gerenciamento, e em seguida um menu se apresenta para ele com as opções que ele poderá realizar
# Caso o retorno seja 18, retorno ao menu
# Caso o retorno seja desconhecido, retorno ao menu
function MDAEH(){
date > /tmp/datahora.txt
dialog --textbox /tmp/datahora.txt 0 0
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --msgbox "Erro $?" 0 0; menu;;
esac
}
 # a data e a hora irão aparecer
 # Caso o retorno seja 0, retorno ao menu
 # Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
 # Caso o retorno seja desconhecido, retorno ao menu
function CALEN(){
dialog --title "Calendário" --calendar '' 0 0
case $? in
	*) menu;;
esac
}
# função calendário irá aparecer
# Caso o retorno seja desconhecido, retorno ao menu

function EDATA(){
mes=$( dialog --stdout --inputbox "Mês:" 0 0 )
case $? in
	1|255) menu;;
esac
# Função para a alterar a data
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
dia=$( dialog --stdout --inputbox "Dia:" 0 0 )
case $? in
	1|255) menu;;
esac
# Pede para digitar um dia ao usuário
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
ano=$( dialog --stdout --inputbox "Ano:" 0 0 )
case $? in
	1|255) menu;;
esac
# Pede para digitar um ano ao usuário
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
hora=$( dialog --stdout --inputbox "Hora:" 0 0 )
case $? in
	1|255) menu;;
esac
# Pede para digitar a hora ao usuário
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
minuto=$( dialog --stdout --inputbox "Minutos:" 0 0 )
case $? in
	1|255) menu;;
esac
# Pede para digitar os minutos ao usuário
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
date $mes$dia$hora$minuto$ano
date > /tmp/data.txt
dialog --textbox /tmp/data.txt 0 0
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --msgbox "Erro $?" 0 0; menu;;
esac
}
# O texto informando as opções fornecidas pelo usuário aparecem
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos

function EHORA(){
horas=$(dialog					\
		--stdout			\
		--title "Ajustar o relógio"	\
		--timebox "/nDica: use as setas e o TAB" 0 0 )
date +%T -s $horas
date +%T > /tmp/hora.txt
dialog --textbox /tmp/hora.txt 0 0
# Função para alterar a hora 
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --msgbox "Erro $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function INFCP(){
	lscpu > /tmp/cpuinf.txt
	dialog --textbox /tmp/cpuinf.txt 0 0
# Função que mostra as informações da CPU
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function EXDP(){
	fdisk -l > /tmp/cpuinf.txt
	dialog --textbox /tmp/cpuinf.txt 0 0
  # Função que mostra as informações do disco e suas partições
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function MODC(){
	lsmod > /tmp/cpuinf.txt
	dialog --textbox /tmp/cpuinf.txt 0 0
# Função que informa os modulos carregados
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function PCI2(){
	lspci -vv > /tmp/pciinf.txt
	dialog --textbox /tmp/pciinf.txt 0 0
# Função que mostra as informações do barramento PCI
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function UTM(){
	free -h > /tmp/infmem.txt
	dialog --textbox /tmp/infmem.txt 0 0
  # Função que mostra a utilização de memória RAM
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function IND(){
	df -ih > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
# Função que mostra a quantidade de INODES disponiveis
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function KERNEL(){
	uname -v > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
  # Função que mostra a versão do Kernel
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo
function ALLINF(){
	uname -a > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
  # Função que mostra todas as informações do sistema
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function PROCSIS(){
	ps aux > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
  # Função que mostra todos os processos do sistema
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function PROCSISH(){
	pstree > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
# Função que mostra todos os processos do sistema de forma hierarquica
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function KILLPROC(){
	kill=$(dialog --stdout --inputbox "Digite o PID do processo que deseja fechar: " 8 50)
  # Função que encerra os processos
case $? in
	1|255) menu;;
esac
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
	kill -9 $kill
case $? in
	0) dialog --msgbox "Encerrado com sucesso" 0 0; menu;;
	1) dialog --msgbox "Não foi possivel encerrar processo" 0 0; menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, sucesso em encerrar o processo, voltando assim para o script gerenciador de dispositivos
# Caso o retorno seja 1, mensagem de falha, retorno ao menu 
# Caso o retorno seja desconhecido, mostra o erro ocorrido e volta ao menu, para refazer o processo

function ARQPROC(){
	lsof > /tmp/ino.txt
	dialog --textbox /tmp/ino.txt 0 0
  # Função que mostra os arquivos que estão em processo no sistema 
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --infobox "erro: $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos

function ARQPROC(){
lsof > /tmp/ino.txt
dialog --textbox /tmp/ino.txt 0 0
# Função que mostra os arquivos em processo 
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --msgbox "Erro $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos

function VINOD(){
dialog --msgbox "Não se esqueça de usar / quando desejar ver INODES de diretório" 0 0
dialog --msgbox "Digite o caminho completo para arquivos em outros diretórios" 0 0
ino=$( dialog --stdout --inputbox "Nome do arquivo/diretório" 0 0 )
# Função que mostra o INODE
case $? in
	1|255) menu;;
esac
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos
ls -i $ino > /tmp/ino.txt
dialog --title "INODE: $ino" --textbox /tmp/ino.txt 0 0 
case $? in
	0) menu;;
	1|255) menu;;
	*) dialog --msgbox "Erro $?" 0 0; menu;;
esac
}
# Caso o retorno seja 0, retorno ao script gerenciador de dispositivos
# Caso pressione Cancel ou ESC, volta para o script gerenciador de dispositivos

menu
